name: SQL Schema Code Linter

on:
  push:
    branches: [ laboratory-work-4 ] 

jobs:
  SQLLinter:
    runs-on: ubuntu-latest # 4 пробіли від jobs
    
    steps: # 4 пробіли від jobs, 2 пробіли від runs-on (якщо це не було виправлено)
      - name: Checkout Code in Repository # 6 пробілів
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install SQLFluff
        run: python -m pip install sqlfluff # 6 пробілів, 

      - name: Start SQL Linter (Check Correct Schema)
        run: | # 6 пробілів
          python -m sqlfluff lint ${{ github.workspace }}/DataSchema.sql --dialect postgres # 8 пробілів (відступ від run: |)
